name: Obfuscate JS

on:
  workflow_dispatch:
    inputs:
        jsurl:
          description: 'JS下载URL'     
          required: true
          default: ''
        jsname:
          description: 'JS名称'
          required: true
          default: ''
  push:
    branches:
      - main
env:
  JSURL: ${{ inputs.jsurl }}
  JSNAME: ${{ inputs.jsname }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install

      - name: Clone BPB workjs
        run: |
          wget -O $JSNAME $JSURL
      
      - name: Obfuscate BPB worker js
        run: |
          npx javascript-obfuscator --config ./obfs-config.json $JSNAME --output _$JSNAME

      - name: Commit and push built worker
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _$JSNAME
          git commit -m "Obfuscate: update _${{JSNAME}}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
